#ifndef __APP_CONFIG_H
#define __APP_CONFIG_H
#define APP_CONTROL_STACK_WORDS 1536U
#define APP_CAN_STACK_WORDS 768U
#define APP_SUPERVISOR_STACK_WORDS 512U
#define APP_COMMAND_QUEUE_DEPTH 8U
#define APP_CONTROL_PRIORITY 7U
#define APP_CAN_PRIORITY 6U
#define APP_SUPERVISOR_PRIORITY 5U
#define APP_CONTROL_DEADLINE_MS 15U
#endif
