#ifndef __BOARD_CONFIG_H
#define __BOARD_CONFIG_H
#define BOARD_CAN_INSTANCE CAN1
#define BOARD_HAL_TICK_INSTANCE TIM6
#define CAN_RX_QUEUE_DEPTH 32U
#define CAN_TX_QUEUE_DEPTH 64U
#define CAN_TX_MAX_AGE_MS 20U
#endif
