#ifndef __BOARD_CONFIG_H
#define __BOARD_CONFIG_H
#define BOARD_CAN_INSTANCE CAN1
#define BOARD_HAL_TICK_INSTANCE TIM6
#define CAN_RX_QUEUE_DEPTH 32U
#define CAN_TX_QUEUE_DEPTH 64U
#define CAN_TX_MAX_AGE_MS 20U
/* PROVISIONAL Prototype 0 wiring. Verify PCB, pullups, RATE and OLED address. */
#define BOARD_SD_INSTANCE SDIO
#define BOARD_ENCODER_INSTANCE TIM3
#define BOARD_UART_INSTANCE USART1
#define BOARD_I2C_INSTANCE I2C1
#define BOARD_HX_PORT GPIOE
#define BOARD_HX_DOUT_PIN GPIO_PIN_0
#define BOARD_HX_SCK_PIN GPIO_PIN_1
#define BOARD_INPUT_PORT GPIOE
#define BOARD_FORWARD_PIN GPIO_PIN_2
#define BOARD_BACK_PIN GPIO_PIN_3
#define BOARD_SOFT_STOP_PIN GPIO_PIN_4
#define BOARD_TF_DETECT_PORT GPIOC
#define BOARD_TF_DETECT_PIN GPIO_PIN_7
#define BOARD_OLED_ADDRESS (0x3CU << 1)
#endif
