#ifndef __UI_STRINGS_H
#define __UI_STRINGS_H
typedef enum
{
    UI_TEXT_EXECUTE,
    UI_TEXT_RECORD,
    UI_TEXT_HOME,
    UI_TEXT_SMALL,
    UI_TEXT_MEDIUM,
    UI_TEXT_LARGE,
    UI_TEXT_START,
    UI_TEXT_RETURN,
    UI_TEXT_DELETE,
    UI_TEXT_CONFIRM_DELETE,
    UI_TEXT_YES,
    UI_TEXT_NO,
    UI_TEXT_RECORD_START,
    UI_TEXT_RECORDING,
    UI_TEXT_SAVING,
    UI_TEXT_LOADING,
    UI_TEXT_EXECUTING,
    UI_TEXT_DONE,
    UI_TEXT_STOPPED,
    UI_TEXT_ERROR,
    UI_TEXT_INITIALIZING,
    UI_TEXT_CONNECTING,
    UI_TEXT_TO_HOME,
    UI_TEXT_STORAGE_MISSING,
    UI_TEXT_TRACK_UNAVAILABLE,
    UI_TEXT_TOO_LONG,
    UI_TEXT_NOT_CONFIGURED,
    UI_TEXT_COUNT
} UiText;
const char *UiStrings_Get(UiText text);
#endif
